### ISSUE TITLE
[Bug Report] Using setup.py with ROS2 Humble causes warnings during build

### ISSUE THREAD

**Issue by aentinger** [107-systems/l3xz_openmv_camera#31]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### :bug: Bug Report

```bash
--- stderr: l3xz_openmv_camera                   
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
```

**Comment by wuehr1999** [comment]
Hi @aentinger 
the setup.py installation way is no more supported with the newer Python version.
This appears as a complicated and still open issue in colcon, see [colcon core issue 454](https://github.com/colcon/colcon-core/issues/454). Hence, I suggest suppressing this warning until a colcon-/ ROS-wide solution is found.

**Comment by aentinger** [comment]
I just read up on the linked issue ... What a mess. Let's proceed as you've suggested.
